### ISSUE TITLE
Git hooks

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-config#16]
Every once in a while it happens that I forget to run `lint` or `coverage` or some command before pushing, and only realize there was an error through CI. I will have to define git hooks locally for myself, but I was thinking maybe this can also be added to the projects so that automatically before push or before commit at least linting would run. [Husky](https://github.com/typicode/husky) seems interesting and easy to integrate. What do you all think?

**Comment by holgerd77** [comment]
Yes.

**Comment by holgerd77** [comment]
That here is probably something not to be integrated into the ``config`` library but to be used directly in the libraries, since there seems to be no need for additional configuration or scripts?

Just a first-look impression.

Might be worth nevertheless to add a note to the [Technical Reference](https://ethereumjs.readthedocs.io/en/latest/technical.html) section in the ``EthereumJS`` docs.

**Comment by s1na** [comment]
Probably not, I mostly wanted to get your opinion. Although it might be
possible to somehow have a shared config here, depending on the tool we use
for the hooks.
